name: vlang-gridproxy-build-pipeline

on:
    push:
      branches:
        - development
      paths-ignore:
        - '**.md'
    pull_request:
      paths-ignore:
        - '**.md'
    workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up V version latest
      uses: vlang/setup-v@v1
      with:
        stable: true
    - name: Install dependencies
      run: v install https://github.com/freeflowuniverse/crystallib
    - name: Keeping compatibility with old imports in some modules
      run: |
        mkdir -p ~/.vmodules/despiegk/crystallib
        cp -r ~/.vmodules/freeflowuniverse/crystallib/. ~/.vmodules/despiegk/crystallib/.
    - name: Run V fmt
      run: v fmt -verify  ./gridproxy/
    - name: Run V tests
      run: v -stats test ./gridproxy/